#--------------------------通用配置-------------------------
spring:
  application:
    # 应用名
    name: novel
  profiles:
    # 激活特定配置
    active: dev
  jackson:
    generator:
      # JSON 序列化时，将所有 Number 类型的属性都转为 String 类型返回，避免前端数据精度丢失的问题。
      # 由于 Javascript 标准规定所有数字处理都应使用 64 位 IEEE 754 浮点值完成，
      # 结果是某些 64 位整数值无法准确表示（尾数只有 51 位宽）
      write-numbers-as-strings: true
  servlet:
    multipart:
      # 上传文件最大大小
      max-file-size: 500MB
server:
  # 端口号
  port: 8080

--- #---------------------数据库配置---------------------------
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/novel_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root123

--- #---------------------中间件配置---------------------------
spring:
  data:
    # Redis 配置
    redis:
      host: 127.0.0.1
      port: 6379
      password:

--- #----------------------安全配置----------------------------
spring:
  # Spring Boot 应用管理和监控
  # boot:
  #   admin:
  #     client:
  #       # 是否开启 Spring Boot Admin 客户端
  #       enabled: false
  #       # Spring Boot Admin 服务端注册地址
  #       url: http://localhost:8080
  #       # Spring Boot Admin 服务端认证用户名
  #       username: novel
  #       # Spring Boot Admin 服务端认证密码
  #       password: novel
  #       instance:
  #         metadata:
  #           # SBA Client
  #           user.name: ${spring.security.user.name}
  #           user.password: ${spring.security.user.password}
  security:
    user:
      name: ENDPOINT_ADMIN
      password: ENDPOINT_ADMIN
      roles: ENDPOINT_ADMIN

--- #--------------------接口文档配置---------------------------
springdoc:
  api-docs:
    enabled: false

--- #---------------------自定义配置----------------------------
novel:
  # 跨域配置
  cors:
    # 允许跨域的域名
    allow-origins:
      - http://localhost:1024
      - http://localhost:8080
      - http://127.0.0.1:8888
  # JWT密钥
  jwt:
    secret: E66559580A1ADF48CDD928516062F12E
  # XSS 过滤配置
  xss:
    # 过滤开关
    enabled: true
    # 排除链接
    excludes:
      - /system/notice/*
  file:
    # 文件上传配置
    upload:
      # 上传路径
      path: upload


--- #------------------- dev 特定配置---------------------------
spring:
  config:
    activate:
      on-profile: dev
springdoc:
  api-docs:
    enabled: true

--- #------------------- test 特定配置--------------------------
# spring:
#   config:
#     activate:
#       on-profile: test

--- #-------------------- prod 特定配置-------------------------
# spring:
#   config:
#     activate:
#       on-profile: prod
#   data:
    # Redis 配置
    # redis:
    #   host: 127.0.0.1
    #   port: 6379
    #   password:


